version: '3.7'

services:
  dac-portal-frontend:
    build:
      context: ./DAC-Portal/DAC-Portal-frontend
      dockerfile: Dockerfile
    ports:
      - 3080:3080
    env_file:
      - ./DAC-Portal/DAC-Portal-frontend/.env
    volumes:
      - ./DAC-Portal/DAC-Portal-frontend/src:/app/src
    depends_on:
      - mongo
      - keycloak
    networks:
      dac-network:
        ipv4_address: 172.21.0.14
  dac-portal-backend:
    build: 
      context: ./DAC-Portal/DAC-Portal-backend
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    env_file:
      - ./DAC-Portal/DAC-Portal-backend/.env
    volumes:
      - ./DAC-Portal/DAC-Portal-backend/src:/usr/src/app/src
    depends_on:
      - mongo
    networks:
      dac-network:
        ipv4_address: 172.21.0.19
  permissions-api:
    build:
      context: ./Permissions-API
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./Permissions-API/src:/app/src
    env_file:
      - ./Permissions-API/.env
    depends_on:
      - mongo
      - keycloak
      - rabbitmq
    networks:
      dac-network:
        ipv4_address: 172.21.0.11
  mariadb:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - "./ipc-test-data/mariadb/:/var/lib/mysql/"
    networks:
      dac-network:
        ipv4_address: 172.21.0.21
  nextcloud-app:
    image: nextcloud:19.0.0
    restart: always
    ports:
      - "7080:80"
    links:
      - mariadb
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
    volumes:
      - "./ipc-test-data/nextcloud/config/:/var/www/html/config/"
      - "./ipc-test-data/nextcloud/data/:/var/www/html/data/"
      - "./ipc-test-data/nextcloud/custom_apps/:/var/www/html/custom_apps/"
    networks:
      dac-network:
        ipv4_address: 172.21.0.20
  dac-management:
    build:
      context: ./DAC-Management-Portal
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - "./DAC-Management-Portal/src:/app/src"
      - "./DAC-Management-Portal/pages:/app/pages"
      - "./DAC-Management-Portal/styles:/app/styles:"
    env_file:
      - ./DAC-Management-Portal/.env
    networks:
      dac-network:
        ipv4_address: 172.21.0.22
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      dac-network:
        ipv4_address: 172.21.0.13
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    volumes:
      - "./ipc-test-data/keycloak/realms:/opt/jboss/keycloak/imports"
      - "./ipc-plugins/keycloak:/opt/jboss/keycloak/standalone/deployments"
    command:
      - '-b 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.migration.strategy=IGNORE_EXISTING'
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      dac-network:
        ipv4_address: 172.21.0.12
  mongo:
    image : mongo:4.4
    hostname: mongo
    restart: on-failure
    environment:
      PUID: 1000
      PGID: 1000
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICASET}
    volumes:
      - "./ipc-test-data/mdbdata:/data/db"
      - "./keyfile:/opt/keyfile/keyfile"
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: "--bind_ip_all --keyFile /opt/keyfile/keyfile --replSet rs0"
    networks:
      dac-network:
        ipv4_address: 172.21.0.10
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      dac-network:
        ipv4_address: 172.21.0.24
  subscriber:
    build:
      context: ./DAC-Notify
      dockerfile: Dockerfile
    env_file:
      - ./DAC-Notify/.env
    volumes:
      - "./DAC-Notify/subscriber-data.js:/app/subscriber-data.js"
      - "./DAC-Notify/subscriber-users.js:/app/subscriber-users.js"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=180 -- npm run subscribe'
    networks:
      dac-network:
        ipv4_address: 172.21.0.23
networks:
  dac-network:
    ipam:
      config:
        - subnet: 172.21.0.0/24

